package com.igpgroup17.studentpals.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.*;

import java.sql.Time;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "events")
public class Event {

    @DynamoDBHashKey(attributeName = "EventID")
    @DynamoDBAutoGeneratedKey
    private String eventID;

    @DynamoDBAttribute(attributeName = "Name")
    private String name;

    @DynamoDBAttribute(attributeName = "Description")
    private String description;

    @DynamoDBAttribute(attributeName = "OrganiserID")
    private String organiserID;

    @DynamoDBAttribute(attributeName = "GoingUsersIDs")
    private String[] goingUsersIDs;

    @DynamoDBAttribute(attributeName = "InterestedUsersIDs")
    private String[] interestedUsersIDs;

    @DynamoDBAttribute(attributeName = "Likes")
    private int likes;

    @DynamoDBAttribute(attributeName = "State")
    private String state;

    @DynamoDBAttribute(attributeName = "ScheduledTime")
    private Time scheduledTime;

}